export const START_TIMER = 'START_TIMER'
export const STOP_TIMER = 'STOP_TIMER'
export const RESET_TIMER = 'RESET_TIMER'
export const ADD_TIME = 'ADD_TIME'
export const REMOVE_TIME = 'REMOVE_TIME'
export const CLEAR_TIMES = 'CLEAR_TIMES'
