// flow-typed signature: 68143c779205fa1a9e6609a4856e6825
// flow-typed version: <<STUB>>/blyss-loader_v^1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blyss-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blyss-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'blyss-loader/index' {
  declare module.exports: $Exports<'blyss-loader'>;
}
declare module 'blyss-loader/index.js' {
  declare module.exports: $Exports<'blyss-loader'>;
}
