// flow-typed signature: 36cd0ab6c2c7517264a9ad04d0ede197
// flow-typed version: <<STUB>>/bulma-stylus_v^0.4.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma-stylus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma-stylus' {
  declare module.exports: any;
}
