// flow-typed signature: 18e581e1325007d817d38b2f7ee76101
// flow-typed version: <<STUB>>/scrambo_v^0.3.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scrambo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scrambo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scrambo/lib/cli' {
  declare module.exports: any;
}

declare module 'scrambo/lib/scramblers/clock' {
  declare module.exports: any;
}

declare module 'scrambo/lib/scramblers/minx' {
  declare module.exports: any;
}

declare module 'scrambo/lib/scramblers/NNN' {
  declare module.exports: any;
}

declare module 'scrambo/lib/scramblers/pyram' {
  declare module.exports: any;
}

declare module 'scrambo/lib/scramblers/skewb' {
  declare module.exports: any;
}

declare module 'scrambo/lib/scramblers/sq1' {
  declare module.exports: any;
}

declare module 'scrambo/lib/scrambo' {
  declare module.exports: any;
}

declare module 'scrambo/lib/util' {
  declare module.exports: any;
}

declare module 'scrambo/scrambo' {
  declare module.exports: any;
}

declare module 'scrambo/test' {
  declare module.exports: any;
}

declare module 'scrambo/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scrambo/lib/cli.js' {
  declare module.exports: $Exports<'scrambo/lib/cli'>;
}
declare module 'scrambo/lib/scramblers/clock.js' {
  declare module.exports: $Exports<'scrambo/lib/scramblers/clock'>;
}
declare module 'scrambo/lib/scramblers/minx.js' {
  declare module.exports: $Exports<'scrambo/lib/scramblers/minx'>;
}
declare module 'scrambo/lib/scramblers/NNN.js' {
  declare module.exports: $Exports<'scrambo/lib/scramblers/NNN'>;
}
declare module 'scrambo/lib/scramblers/pyram.js' {
  declare module.exports: $Exports<'scrambo/lib/scramblers/pyram'>;
}
declare module 'scrambo/lib/scramblers/skewb.js' {
  declare module.exports: $Exports<'scrambo/lib/scramblers/skewb'>;
}
declare module 'scrambo/lib/scramblers/sq1.js' {
  declare module.exports: $Exports<'scrambo/lib/scramblers/sq1'>;
}
declare module 'scrambo/lib/scrambo.js' {
  declare module.exports: $Exports<'scrambo/lib/scrambo'>;
}
declare module 'scrambo/lib/util.js' {
  declare module.exports: $Exports<'scrambo/lib/util'>;
}
declare module 'scrambo/scrambo.js' {
  declare module.exports: $Exports<'scrambo/scrambo'>;
}
declare module 'scrambo/test.js' {
  declare module.exports: $Exports<'scrambo/test'>;
}
declare module 'scrambo/test/test.js' {
  declare module.exports: $Exports<'scrambo/test/test'>;
}
