// flow-typed signature: 011ccd4ef44bbca0c2b5d26f03460ccc
// flow-typed version: <<STUB>>/stylint-stylish_v^1.4.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylint-stylish'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylint-stylish' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylint-stylish/index' {
  declare module.exports: $Exports<'stylint-stylish'>;
}
declare module 'stylint-stylish/index.js' {
  declare module.exports: $Exports<'stylint-stylish'>;
}
